
dist: trusty
sudo: required

language: java

deploy:
  provider: elasticbeanstalk
  zip_file: target/bookstore-0.0.1-SNAPSHOT.jar
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: eu-central-1
  app: realBookstore
  env: realBookstore-env
  skip_cleanup: true
  bucket_name: elasticbeanstalk-eu-central-1-364022542967